<?php 
return array (
  'timestamp' => 1689932774,
  'site_id' => 1,
  'group' => 'posts',
  'key' => 198,
  'type' => 'object',
  'timeout' => 1691142374,
  'data' => 
  (object) array(
     'ID' => 198,
     'post_author' => '1',
     'post_date' => '2023-07-20 02:38:40',
     'post_date_gmt' => '2023-07-20 02:38:40',
     'post_content' => '',
     'post_title' => 'Barks and Bytes',
     'post_excerpt' => '',
     'post_status' => 'publish',
     'comment_status' => 'closed',
     'ping_status' => 'closed',
     'post_password' => '',
     'post_name' => 'barks-and-bytes',
     'to_ping' => '',
     'pinged' => '',
     'post_modified' => '2023-07-20 02:38:40',
     'post_modified_gmt' => '2023-07-20 02:38:40',
     'post_content_filtered' => '',
     'post_parent' => 0,
     'guid' => 'https://impremis.com/barepetswp/?page_id=198',
     'menu_order' => 0,
     'post_type' => 'page',
     'post_mime_type' => '',
     'comment_count' => '0',
     'filter' => 'raw',
  ),
);
/*@DOCKET_CACHE_EOF*/